application: khan-netherlands
version: 8
runtime: python27
api_version: 1
default_expiration: "365d"
threadsafe: no

libraries:
- name: markupsafe
  version: "0.15"
- name: jinja2
  version: "2.6"
# This also brings in webapp2_extras:
- name: webapp2
  version: "2.3"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*_test\.py
- ^(.*/)?sample_data/.*
- ^(.*/)?khan-exercises/test/.*
- ^(.*/)?presskit/.*
- ^(.*/)?deploy/.*
- ^(.*/)?images/power-mode/badges/readme
- ^(.*/)?javascript/testbase\.js
- ^(.*/)?javascript/test/.*
- ^(.*/)?.*_test\.html
- ^requirements\.txt
- ^third-party/agar
- ^third-party/agar-src
- ^testutil
- ^tools

handlers:
- url: /videos
  static_dir: offline/Khan Academy/videos

- url: /flvplayer
  static_dir: flvplayer

- url: /soundmanager
  static_dir: soundmanager

- url: /stylesheets
  static_dir: stylesheets

- url: /favicon.ico
  static_files: images/favicon.ico
  mime_type: image/x-icon
  upload: images/favicon.ico

- url: /google663128d2a1a65b87.html
  static_files: google663128d2a1a65b87.html
  upload: google663128d2a1a65b87.html

- url: /images/favicon.ico
  static_files: images/favicon.ico
  mime_type: image/x-icon
  upload: images/favicon.ico

- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript

- url: /sounds
  static_dir: sounds

# Begin GTV integration
- url: /gtv/css
  static_dir: gtv/css

- url: /gtv/images
  static_dir: gtv/images

- url: /gtv/js
  static_dir: gtv/js

- url: /gtv/fullscreen.html
  static_files: gtv/fullscreen.html
  upload: gtv/fullscreen.html

- url: /gtv/
  static_files: gtv/index.html
  upload: gtv/index.html

- url: /gtv.*
  script: gtv.main.application
# End GTV integration

# Begin khan-exercises integration
- url: /khan-exercises/khan-exercise.js
  static_files: khan-exercises/khan-exercise.js
  upload: khan-exercises/khan-exercise.js

- url: /khan-exercises/utils
  static_dir: khan-exercises/utils

- url: /khan-exercises/css
  static_dir: khan-exercises/css

- url: /khan-exercises/images
  static_dir: khan-exercises/images

- url: /khan-exercises/(hashed.+\.js)
  static_files: khan-exercises/\1
  upload: khan-exercises/(hashed.+\.js)
# End khan-exercises integration

- url: /downloads/(.*)
  static_files: downloads/\1
  upload: downloads/(.*)

- url: /remote_api
  script: google.appengine.ext.remote_api.handler.application
  login: admin

- url: /_ah/queue/deferred_problemlog
  script: google.appengine.ext.deferred.application
  login: admin

- url: /_ah/queue/deferred_stacklog
  script: google.appengine.ext.deferred.application
  login: admin

- url: /_ah/queue/deferred_videolog
  script: google.appengine.ext.deferred.application
  login: admin

- url: /_ah/queue/deferred_log_summary
  script: google.appengine.ext.deferred.application
  login: admin

- url: /_ah/queue/deferred_import
  script: google.appengine.ext.deferred.application
  login: admin

- url: /_ah/queue/deferred_topics-set-default-queue
  script: google.appengine.ext.deferred.application
  login: admin

- url: /admin/.*
  script: main.application
  login: admin

- url: /mapreduce(/.*)?
  script: third_party.mapreduce.main.APP
  login: admin

- url: /api/.*
  script: api.main.application

- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static
  expiration: "300s"

- url: /gae_mini_profiler/.*
  script: gae_mini_profiler.main.application

- url: /gae_bingo/static
  static_dir: gae_bingo/static
  expiration: "300s"

- url: /gae_bingo/tests/.*
  script: gae_bingo.tests.main.application

- url: /gae_bingo/.*
  script: gae_bingo.main.application

- url: /gandalf/static
  static_dir: gandalf/static
  expiration: "300s"

- url: /gandalf/tests/.*
  script: gandalf.tests.main.application

- url: /gandalf?.*
  script: gandalf.main.application

- url: .*
  script: main.application

builtins:
- appstats: on
- deferred: on
- remote_api: on

inbound_services:
- warmup

admin_console:
  pages:
    - name: AppStats
      url: /_ah/stats
    - name: Mapreduce
      url: /mapreduce
    - name: YouTube Sync
      url: /admin/youtubesync
