({
	"nl" : {
		"list1"		: 'Vlieger',
		"list2"		: 'Trapezium',
		"list3"		: 'Gelijkbenig trapezium',
		"list4"		: 'Parallelogram',
		"list5"		: 'Ruit',
		"list6"		: 'Rechthoek',
		"list7"		: 'Vierkant',
		"list8"		: 'Geen van de bovenstaande',
		
		"problem1"	: 'Welk type vierhoek is dit? Geef een zo nauwkeurig mogelijk antwoord.',
	
		"hint1"		: 'Deze figuur heeft 2 paralelle zijden.',
		"hint2"		: 'Het heeft ook 2 paar aangrenzende hoeken die elkaars supplement zijn.',
		"hint3"		: 'Het is een trapezium.',
		"hint4"		: 'Deze figuur heeft 2 paralelle zijden.',
		"hint5"		: 'Het heeft ook 2 paar aangrenzende hoeken die elkaars supplement zijn.',
		"hint6"		: 'Het is een trapezium.',
		"hint7"		: 'Maar de benen zijn gelijk, dus is het een gelijkbenig trapezium.',
		"hint8"		: 'De overstaande hoeken van deze vierhoek zijn gelijk..',
		"hint9"		: 'Aan elkaar grenzende hoeken zijn elkaars supplement.',
		"hint10"	: 'Het heeft 2 paar evenwijdige zijden.',
		"hint11"	: 'De paralelle zijden zijn gelijk.',
		"hint12"	: 'Daarom is het een paralellogram.',
		"hint13"	: 'Deze vierhoek heeft 2 paar gelijke zijden.',
		"hint14"	: 'De hoeken zijn 90°.',
		"hint15"	: 'Daarom is het een rechthoek.',
		"hint16"	: 'Deze vierhoek heeft 2 paar gelijke zijden.',
		"hint17"	: 'De hoeken zijn 90°.',
		"hint18"	: 'Alle zijden zijn gelijk.',
		"hint19"	: 'Daarom is het een vierkant.',
		"hint20"	: 'Deze vierhoek heeft 2 paar gelijke zijden.',
		"hint21"	: 'Deze zijdes zijn aangrenzend.',
		"hint22"	: 'Het heeft ook een paar met gelijke hoeken, liggend tussen de niet-gelijke zijdes.',
		"hint23"	: 'Het is een vlieger.',
		"hint24"	: 'Van deze vierhoek zijn alle zijden gelijk.',
		"hint25"	: 'Dus is het een ruit.'
		}
})