// todo(dmnd) DRY this up. Current situation where the nested property points
// to an autogenerated sluggified version of a title is fragile and weird.
Socrates.Data["xyAuNHPsq-g"] = {
    Events: [
        new Socrates.Bookmark({
            time: "0m0s",
            title: "What is a matrix?"
        }),
        new Socrates.Bookmark({
            time: "0m59s",
            title: "Dimensions of a matrix"
        }),
        new Socrates.Question({
            time: "2m5.7s",
            title: "Dimensions of a matrix",
            nested: "dimensions-of-a-matrix",
            youtubeId: "xyAuNHPsq-g",
            id: 1,
            correctData: {rows: "4", cols: "5"}
        }),
        new Socrates.Bookmark({
            time: "2m6s",
            title: "Referencing elements in a matrix"
        }),
        new Socrates.Question({
            time: "3m20s",
            title: "Referencing elements in a matrix",
            nested: "referencing-elements-in-a-matrix",
            youtubeId: "xyAuNHPsq-g",
            id: 2,
            correctData: {answer: "2"}
        }),
        new Socrates.Bookmark({
            time: "3m28s",
            title: "What are matrices used for?"
        }),
        new Socrates.Question({
            time: "4m23.9s",
            title: "What are matrices used for?",
            nested: "what-are-matrices-used-for",
            youtubeId: "xyAuNHPsq-g",
            id: 3,
            correctData: {answer: [true, true, true, true, true, true]}
        }),
        new Socrates.Bookmark({
            time: "4m42s",
            title: "Defining matrix addition"
        }),
        new Socrates.Question({
            time: "6m31s",
            title: "Defining matrix addition",
            nested: "defining-matrix-addition",
            youtubeId: "xyAuNHPsq-g",
            id: 4
        }),
        new Socrates.Bookmark({
            time: "6m31s",
            title: "Matrix addition"
        }),
        new Socrates.Bookmark({
            time: "7m39s",
            title: "Commutativity of matrix addition"
        }),
        new Socrates.Question({
            time: "8m11s",
            title: "Commutativity of matrix addition",
            nested: "commutativity-of-matrix-addition",
            youtubeId: "xyAuNHPsq-g",
            id: 5
        }),
        new Socrates.Question({
            time: "8m11s",
            title: "Matrix addition",
            youtubeId: "xyAuNHPsq-g",
            id: 6,
            correctData: {answer: [[80, 23], [13, 25]]}
        }),
        new Socrates.Bookmark({
            time: "8m11s",
            title: "Matrix subtraction"
        }),
        new Socrates.Bookmark({
            time: "9m44s",
            title: "Matrices that can be added"
        }),
        new Socrates.Question({
            time: "11m17s",
            title: "Matrices that can be added",
            nested: "matrices-that-can-be-added",
            youtubeId: "xyAuNHPsq-g",
            id: 8,
            correctData: {answer: [false, false, true, true, false]}
        }),
        new Socrates.Bookmark({
            time: "11m17s",
            title: "Matrix terminology"
        }),
        new Socrates.Question({
            time: "11m50s",
            title: "Matrix terminology",
            nested: "matrix-terminology",
            youtubeId: "xyAuNHPsq-g",
            id: 9,
            correctData: {answer: {
                "scalar": {"scalar": true, "row-vector": false, "column-vector": false, "matrix": false},
                "column-vector": {"scalar": false, "row-vector": false, "column-vector": true, "matrix": true},
                "row-vector": {"scalar": false, "row-vector": true, "column-vector": false, "matrix": true},
                "matrix": {"scalar": false, "row-vector": false, "column-vector": false, "matrix": true}
            }}
        })
    ],

    Skips: [
        {span: ["25.5s", "42s"]},
        {span: ["1m40s", "2m2s"]}
    ]
};
